### PR TITLE
81 issues with token minting and hardware wallet assosiation

### LINKED ISSUE #81: Issues with Token Minting and Hardware Wallet Assosiation
Users are encountering two significant problems wiht our Blockain interaction.

Token Minting Error: Some users are unable to mint their tokens. Despite following the correct steps, they experience errors during the minting process. This issue needs immediate attention to ensure all users can successfully mint tokens on the Cardano blockchain.

Hardware Wallet Compatibility: Certain users are facing difficulties using their hardware wallets (Ledger Nano S, Ledger Nano S Plus). The integration with hardware wallets is not functioning as expected.

### PR DESCRIPTION
**Pull request by santiagoziel**

### CODE REVIEW

File: blockchain/src/wallet/routes-wallet.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+import { Request } from "npm:express-jwt@8.4.1"
+import { requestCatchError } from "../catch-error.ts";
+
+import {CardanoDsl} from "./lucid-dsl.ts"
+import { Resolution } from "../utypes.ts";
+
+export const walletRoutes = (cardanoDSL: CardanoDsl) => {
+    const router = Router() 
+
+    router.post("/selfTx", requestCatchError(async (request: Request, response: Response) => {
```
Comment (VledicFranco) [inline blockchain/src/wallet/routes-wallet.ts]: We use dash-snake-case for endpoints :)

File: blockchain/src/wallet/lucid-dsl.ts [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+    static async loadFromEnv(): Promise<CardanoDsl>{ 
+        const projectId = await stringOrError("BLOCKFROST_API_KEY")
+        const network: Network = await stringOrError("CARDANO_NETWORK")
+        const blockfrostAPILink = network == "Mainnet" ? "https://cardano-mainnet.blockfrost.io/api/v0" : "https://cardano-preprod.blockfrost.io/api/v0"
+        const lucid = await Lucid.new(new Blockfrost(blockfrostAPILink, projectId), network)
+        return new CardanoDsl(lucid)
+    }
+
+    buildSelfTx = async (stakeAddress: string): Promise<Resolution<string>> => {
```
Comment (VledicFranco) [inline blockchain/src/wallet/lucid-dsl.ts]: We should have the top-level DSL to be a bit more expressive, as in each specific use case we have, like "walletAuthenticationSelfTx", and then maybe have lower level reusable DSLs that do lower level things, like actually building a self tx

File: frontend/apps/account/account-thunks.ts [hunk 3]
```diff
@@ -189,6 +189,21 @@ export const AccountThunks = {
                 return displayErrorAndHeal(`Somethig went wrong: ${signature.reason}`) 
             dispatch(actions.setAssociateProcessState({ ctype: "loading", details: "Updating inventory..." }))
             dispatch(actions.addStakeAddress(stakeAddress))
+            */
+            /*TEST*/
+            dispatch(actions.setAssociateProcessState({ ctype: "loading", details: "Building Auth Tx" }))
```
Comment (VledicFranco) [inline frontend/apps/account/account-thunks.ts]: Nice! Test-driven development FTW

**Review by VledicFranco — APPROVED** [review]
